create table
  public.tasks (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    updated_at timestamp with time zone not null default (now() at time zone 'utc'::text),
    name text not null,
    completed boolean null default false,
    constraint tasks_pkey primary key (id),
    constraint tasks_id_key unique (id)
  ) tablespace pg_default;