on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Check lint
        run: ./gradlew ktlintCheck

  test:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Run tests
        run: ./gradlew test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Set up SQLite
        run: sudo apt-get install sqlite3
      - name: Run SQLite command
        run: |
          sqlite3 kwtodo.db "VACUUM;"
      - name: Restore SQLite database (if exists)
        uses: actions/download-artifact@v4
        with:
          name: sqlite-db
          path: ./
      - name: Build application
        run: ./gradlew assemble
      - name: Run application
        env:
          PORT: 8080
          DATABASE_PATH: ./kwtodo.db
        run: |
          java -jar ./server/build/libs/server-all.jar
      - name: Save SQLite database
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-db
          path: ./kwtodo.db
